### ISSUE TITLE
I cannot get Receiver Mode to work for raspberry Pi 4

### ISSUE THREAD

**Issue by Sam-Markey** [epeters13/pyLoraRFM9x#4]
Hi,

I managed to get a raspberry pi 4 to transmit messages, but when set to receiver mode, it cannot receive the messages sent from the Arduino. Everything is on the same frequency.

If you could help, that would be great! Thank you.

`
import time
from pyLoraRFM9x import LoRa, ModemConfig
import zlib
import sys

def on_recv(self, message):
    print("From:", self.header_from)
    print("Received:", self.message)
    print("RSSI: {}; SNR: {}".format(self.rssi, self.snr))
    print(message)

lora = LoRa(1, 5, 255, reset_pin=25, freq=868, acks=False, receive_all=True)
lora.on_recv = on_recv
lora.set_mode_rx()

while 1:
    lora.on_recv
`

**Comment by oldhaapi** [comment]
You don't invoke lora.on_recv directly -- it gets called via an interrupt call-back. The "while" at the bottom should be more like:
```

while True:
    time.sleep(0.5)
```

**Comment by patryk-m-malinowski** [comment]
I have exactly the same issue where the pi can transmit but not receive. Using @oldhaapi 's suggestion didn't work. Grateful if anyone offers help. My rpi is the rpi 3 model b with Raspberry Pi OS Bullseye.

**Comment by oldhaapi** [comment]
Sam-Markey's code above does not have a modem_config parameter in the LoRa() init code, but mine does:

    def radio_init(self):
        self.rfm9x_detected = False

        already_found = devlocConfig['Intrinsics'].get('Sensor_gw', None)
        if already_found is not None and not already_found:
            return self.rfm9x_detected

        try:
            self.rfm9x = LoRa(
                self.lorapins['spi'],
                0,
                self.lorapins['intr'],
                0,
                reset_pin=self.lorapins['reset'],
                modem_config=ModemConfig.Bw125Cr45Sf128,
                tx_power=self.tx_power,
                acks=False)
            self.rfm9x.on_recv = self.on_recv
            self.rfm9x.set_mode_rx()
            self.rfm9x_detected = True
        except (AssertionError, RuntimeError) as error:
            syslog.syslog(syslog.LOG_ERR, "Init - No rfm9x detected or incompatible version: {}".format(error))
        except Exception as e:
            syslog.syslog(syslog.LOG_ERR, f"LORA init error: {e}")
        return self.rfm9x_detected

**Comment by patryk-m-malinowski** [comment]
I've tried experimenting with all the modem configs without success.

**Comment by oldhaapi** [comment]
What's your on_recv() method doing? It is an interrupt call-back, so you can't make a blocking call from it, including print(). Mine puts the packet payload on a Queue and notifies a Condition.

**Comment by patryk-m-malinowski** [comment]
It did have the prints in it just like in the example code. I then removed the prints and made it set a global boolean variable which is then read in the main thread.

Here is my code if this helps:
```
from pyLoraRFM9x import LoRa, ModemConfig
from time import sleep

MODE='rx'
success=False
# This is our callback function that runs when a message is received
def on_recv(payload):
    #print("From:", payload.header_from)
    #print("Received:", payload.message)
    #print("RSSI: {}; SNR: {}".format(payload.rssi, payload.snr))
    #open("success.txt", 'w').close()
    global success
    success = True

# Use chip select 1. GPIO pin 5 will be used for interrupts and set reset pin to 25
# The address of this device will be set to 255
lora = LoRa(1, 5, 255, freq=868, reset_pin=25, receive_all=True, acks=False)
print("Init done")
lora.on_recv = on_recv
if MODE == 'rx':
    lora.set_mode_rx()
    try:
        while True:    
            if success:
                print("Receive success")
            sleep(0.5)
    except KeyboardInterrupt:
        pass
else:
    lora.set_mode_tx()    

    # Send a message to a recipient device with address 10
    # Retry sending the message twice if we don't get an  acknowledgment from the recipient
    try:
        while True:
            print("Sending")
            message = "This is a test message"
            status = lora.send_to_wait(message, 10, retries=2)
            sleep(2)
    except KeyboardInterrupt:
        pass

print("Closing...")
lora.close()
```

**Comment by oldhaapi** [comment]
Can't see anything wrong with your code. We had to play with the wiringpi module (eventually discarded it for a bcm approach) to get pin mappings correctly initialized. 
Our LoRa init would be LoRa(0, 0, 5, 0,reset_pin=26,modem_config=ModemConfig.Bw125Cr45Sf128,tx_power=25,acs=False)

**Comment by patryk-m-malinowski** [comment]
Something looks a little weird with your code. You set the fourth argument of the LoRa constructor (i.e. reset pin) to 0 but then set it again using the keyword argument reset_pin to 26. Also, can you acutally use GPIO0 for the interrupts because that pin is EEPROM serial data i2c?

**Comment by oldhaapi** [comment]
I may have mis-transcribed. My point was that the pins differ between the
wiringpi model and bcm model.

**Comment by patryk-m-malinowski** [comment]
So, it turns out that when I transmit with my other RPi w/ this library instead of transmitting w/ my ESP32, the other pi receives successfully! This means the ESP32 library transmitted in a format that this library didn't understand. I've rewritten the ESP32 library so that its steps for txing exactly match this library and now it all works perfectly. @Sam-Markey 's Arduino definitely has the same issue. I will open source my Arduino/ESP32 library once it's polished.
